export const CASTLE_LIST_REQUEST = 'CASTLE_LIST_REQUEST';
export const CASTLE_LIST_SUCCESS = 'CASTLE_LIST_SUCCESS';
export const CASTLE_LIST_FAIL = 'CASTLE_LIST_FAIL';

export const CASTLE_DETAILS_REQUEST = 'CASTLE_DETAILS_REQUEST';
export const CASTLE_DETAILS_SUCCESS = 'CASTLE_DETAILS_SUCCESS';
export const CASTLE_DETAILS_FAIL = 'CASTLE_DETAILS_FAIL';